apiVersion: apps/v1
kind: Deployment
metadata:
  name: fablink-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fablink-backend
  template:
    metadata:
      labels:
        app: fablink-backend
    spec:
      serviceAccountName: fablink-backend-sa # IRSA 사용(IAM Role for Service Accounts)
      containers:
        - name: fablink-backend
          image: fablink-backend:latest
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: fablink-config
            - secretRef:
                name: fablink-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
