apiVersion: v1
kind: Secret
metadata:
  name: fablink-secrets
type: Opaque
data:
  # Django Secret Key (Base64 encoded)
  DJANGO_SECRET_KEY: ""
  
  # Aurora DB 인증 정보 (Base64 encoded)
  DB_USER: ""
  DB_PASSWORD: ""
  
  # 외부 API 키들 (필요시, Base64 encoded)
  # EXTERNAL_API_KEY: ""

# AWS 자격증명은 IRSA 사용:
# - ServiceAccount에 IAM Role 연결
# - Pod에서 AWS SDK가 자동으로 Role 사용
# - DynamoDB, S3 등 AWS 서비스 접근 가능
