apiVersion: v1
kind: ConfigMap
metadata:
  name: fablink-config
  namespace: fablink-prod
  labels:
    app: fablink-backend
    environment: prod
data:
  # Django 환경 설정
  DJANGO_ENV: "prod"
  DEBUG: "False"
  
  # 도메인 및 CORS 설정
  ALLOWED_HOSTS: "api.fab-link.org,fab-link.org,localhost"
  CORS_ALLOWED_ORIGINS: "https://fab-link.org"
  
  # 데이터베이스 설정 (Aurora PostgreSQL)
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "fablink"
  DB_HOST: "fablink-aurora-cluster.cluster-cr2c0e2q6qeb.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "5432"
  
  # DynamoDB 설정 (필요시)
  USE_DYNAMODB: "False"
  DYNAMODB_REGION: "ap-northeast-2"
  DYNAMODB_TABLE_PREFIX: "fablink_prod"
  
  # S3 설정
  USE_S3: "True"
  AWS_STORAGE_BUCKET_NAME: "fablink-prod-uploads"
  AWS_S3_REGION_NAME: "ap-northeast-2"
  
  # 보안 설정 (Production)
  SECURE_SSL_REDIRECT: "False"  # 로드 밸런서에서 SSL 처리
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  SECURE_CONTENT_TYPE_NOSNIFF: "True"
  SECURE_BROWSER_XSS_FILTER: "True"
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"
  
  # 로깅 설정
  LOG_LEVEL: "INFO"
  
  # 모니터링 설정
  SENTRY_ENVIRONMENT: "production"
  
  # 외부 서비스 설정
  PAYMENT_GATEWAY_ENVIRONMENT: "production"
  
  # MongoDB 설정 (필요시)
  MONGODB_URI: "mongodb://localhost:27017"
  MONGODB_DB: "fablink_prod"
  MONGODB_COLLECTION_ORDERS: "orders"
