apiVersion: v1
kind: ServiceAccount
metadata:
  name: fablink-backend-sa
  namespace: fablink-prod
  labels:
    app: fablink-backend
    environment: prod
  annotations:
    # IRSA (IAM Roles for Service Accounts) 설정 (필요시)
    # eks.amazonaws.com/role-arn: arn:aws:iam::853963783084:role/fablink-backend-role
automountServiceAccountToken: true
