apiVersion: apps/v1
kind: Deployment
metadata:
  name: fablink-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: fablink-backend
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
