apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: fablink-dev

# Base의 fablink-backend:latest를 ECR dev 이미지로 변환
images:
  - name: fablink-backend
    newName: 853963783084.dkr.ecr.ap-northeast-2.amazonaws.com/fablink-backend-dev
    newTag: latest

patchesStrategicMerge:
  - configmap-patch.yaml
  - service-patch.yaml
  - deployment-patch.yaml
  - serviceaccount-patch.yaml

commonLabels:
  env: dev
