apiVersion: v1
kind: ServiceAccount
metadata:
  name: fablink-backend-sa
  annotations:
    # IRSA: Dev 환경용 IAM Role (실제 생성된 ARN)
    eks.amazonaws.com/role-arn: arn:aws:iam::853963783084:role/fablink-backend-role-dev
